### ISSUE TITLE
Readme mentions "removeHtml" but function not found

### ISSUE THREAD

**Issue by chrisspiegl** [aimee-gm/text-cleaner#6]
Hi, I just found this package in the search for a way to cleaning up some test.

Overall it does exactly what I need, so thanks for publishing.

I found that in the readme at the top it shows an example with `removeHtml` but in the docs below it's called `stripHtml`?

I think both would work, and maybe even a double name would be helpful for ease of memory.

Thanks,

Chris

**Comment by KonradLinkowski** [comment]
I believe there was meant to be `stripHtml`
